MODEL:
  NAME: "UNet3plus_resnet101"
  NUM_CLASSES: 5
  DEVICE: "cuda:1"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (256, 256)
  TARGET_INPUT_SIZE_TRAIN: (256, 256)
  INPUT_SIZE_TEST: (256, 256)
  SRC_PIXEL_MEAN: [0.069,0.069,0.068]
  SRC_PIXEL_STD: [1.016,1.015,1.015]
  TGT_PIXEL_MEAN: [0.069,0.069,0.068]
  TGT_PIXEL_STD: [1.016,1.015,1.015]
DATASETS:
  DATASET_ROOT: "datasets/MM-WHS"
  SOURCE_TRAIN_DIR: "mr"
  SOURCE_TRAIN_LIST: "mr_train_list.txt"
  SOURCE_TRAIN_label_info: "mr_label_info.p"
  TEST_DIR: "mr"
  TEST_LIST: "mr_test_list.txt"
  VAL_DIR: "mr"
  VAL_LIST: "mr_val_list.txt"
PROCTITLE: "WUADA-CT2MR-full_supervise"
OUTPUT_DIR: "results/full_supervise_ct2mr_u3plus_r101_WUADA"