MODEL:
  NAME: "UNet3plus_resnet101"
  NUM_CLASSES: 4
  DEVICE: "cuda:0"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (192, 192)
  TARGET_INPUT_SIZE_TRAIN: (192, 192)
  INPUT_SIZE_TEST: (192, 192)
  SRC_PIXEL_MEAN: [-0.024,-0.024,-0.025]
  SRC_PIXEL_STD: [1.001,1.000,1.000]
  TGT_PIXEL_MEAN: [-0.023,-0.021,-0.020]
  TGT_PIXEL_STD: [1.011,1.011,1.011]
DATASETS:
  DATASET_ROOT: "datasets/MS-CMRSeg"
  SOURCE_TRAIN_DIR: "bSSFP"
  SOURCE_TRAIN_LIST: "bSSFP_train_list.txt"
  SOURCE_TRAIN_label_info: "bSSFP_label_info.p"
  TEST_DIR: "LGE"
  TEST_LIST: "LGE_test_list.txt"
  VAL_DIR: "LGE"
  VAL_LIST: "LGE_val_list.txt"
PROCTITLE: "WUADA-bSSFP2LGE-source_only"
OUTPUT_DIR: "results/source_only_bssfp2lge_u3plus_r101_WUADA"