from yacs.config import CfgNode as CN

_C = CN()

_C.MODEL = CN()
_C.MODEL.NAME = "UNet3plus_resnet101"
_C.MODEL.NUM_CLASSES = 5
_C.MODEL.DEVICE = "cuda:0"
_C.MODEL.WEIGHTS = ""

_C.INPUT = CN()
_C.INPUT.SOURCE_INPUT_SIZE_TRAIN = (256, 256)
_C.INPUT.TARGET_INPUT_SIZE_TRAIN = (256, 256)
_C.INPUT.INPUT_SIZE_TEST = (256, 256)

_C.INPUT.INPUT_SCALES_TRAIN = True
_C.INPUT.HORIZONTAL_FLIP = True
_C.INPUT.ELASTIC_DEFORMATION = True
_C.INPUT.ROTATION = True
_C.INPUT.BRIGHTNESSCONTRAST = True

_C.INPUT.IGNORE_LABEL = 255
_C.INPUT.SRC_PIXEL_MEAN = [-1.067,-1.068,-1.069]
_C.INPUT.SRC_PIXEL_STD = [1.134,1.134,1.133]
_C.INPUT.TGT_PIXEL_MEAN = [0.069,0.069,0.068]
_C.INPUT.TGT_PIXEL_STD = [1.016,1.015,1.015]

_C.DATASETS = CN()
_C.DATASETS.DATASET_ROOT = "datasets/MM-WHS"
_C.DATASETS.SOURCE_TRAIN_DIR = "ct"
_C.DATASETS.SOURCE_TRAIN_LIST = "ct_train_list.txt"
_C.DATASETS.SOURCE_TRAIN_label_info = "ct_label_info.p"
_C.DATASETS.TARGET_TRAIN_DIR = "mr"
_C.DATASETS.TARGET_TRAIN_LIST = "mr_train_list.txt"
_C.DATASETS.TEST_DIR = "mr"
_C.DATASETS.TEST_LIST = "mr_test_list.txt"
_C.DATASETS.VAL_DIR = "mr"
_C.DATASETS.VAL_LIST = "mr_val_list.txt"

_C.SOLVER = CN()
_C.SOLVER.MAX_ITER = 40000
_C.SOLVER.STOP_ITER = 40000
_C.SOLVER.CHECKPOINT_PERIOD = 5000

_C.SOLVER.FEA_BASE_LR = 1e-4
_C.SOLVER.CLS_BASE_LR = 5e-4
_C.SOLVER.FEA_WEIGHT_DECAY = 1e-4
_C.SOLVER.CLS_WEIGHT_DECAY = 1e-4
_C.SOLVER.FEA_POWER = 0.95
_C.SOLVER.CLS_POWER = 0.7
_C.SOLVER.FEA_MIN_LR = 1e-6
_C.SOLVER.CLS_MIN_LR = 1e-6

_C.SOLVER.BATCH_SIZE = 5
_C.SOLVER.BATCH_SIZE_VAL = 1

_C.SOLVER.SRC_DICE_LOSS = 0.05
_C.SOLVER.SRC_CROSSENTROPY_LOSS = 1.0
_C.SOLVER.SRC_AUX_CROSSENTROPY_LOSS = 0.4
_C.SOLVER.UNCERTAINTY_AWARE_CE_LOSS = 0.1
_C.SOLVER.LCR_TYPE = "l1"

_C.ACTIVE = CN()

_C.ACTIVE.NAME = 'WUADA'
_C.ACTIVE.SETTING = 'RA'
_C.ACTIVE.SELECT_ITER = [10000, 12000, 16000, 18000]
_C.ACTIVE.RATIO = 0.009
_C.ACTIVE.RANDOM_RATIO = 0.001
_C.ACTIVE.RADIUS_K = 1
_C.ACTIVE.RANDOM_PIXS_RATIO = 0.1
_C.ACTIVE.PIXELS = 40

_C.TEST = CN()
_C.TEST.BATCH_SIZE = 1

_C.OUTPUT_DIR = ""
_C.RESUME = "_best_model.pth"
_C.SEED = 1
_C.DEBUG = 0
_C.PROCTITLE = ""
_C.FREE_FOLDER=""
